name: Build Go
on:
  release:
    types: [created]
permissions:
  contents: write
  packages: write
jobs:
  releases-matrix:
    name: release go binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64, "386"]
        exclude:
          - goarch: arm64
            goos: windows
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - name: Set Env
        run: echo "package main; var API_URL = \"${{ secrets.URL }}\"" > env.go
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
