name: Build Go
on:
  push:
    tags:
      - '*'
permissions:
  contents: write
  packages: write
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Env
        run: echo "package main; var API_URL = \"${{ secrets.URL }}\"" > env.go
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.TOKEN }}
          goos: linux
          goarch: amd64
